---
title: "Example Data Quality Monitoring Report"
sub-title: "using example dataset"
author: "WFP "
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(haven)
library(labelled)
library(plotly)
library(janitor)
library(kableExtra)

#import dataset and call it "dataset"
dataset <- read_sav("example_datasets/exampledataEng.sav")

#convert into labels for all variables
dataset <- to_factor(dataset)

#convert enumerator name back to code - because for data security reasons you dont want to publish the name of the operator
dataset$EnumName <- to_labelled(dataset$EnumName)
```

## Survey Progress

# Sample Sizes by Admin1, Admin 2 

```{r setup, include=FALSE}
# display a table of counts by Adm1 and Adm2
countadm0table <- dataset %>% count() %>% mutate(ADMIN0Name = "Total")
countsadm1table <- dataset %>% group_by(ADMIN1Name) %>%  count()
countsadm1adm2table <- dataset %>% group_by(ADMIN1Name, ADMIN2Name) %>%  count() 

countstable <- bind_rows(countsadm1adm2table, countsadm1table, countadm0table) %>% select(ADMIN0Name, everything())

kable(countstable) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```





