# Food Consumption Score

Variable Name | Question Label 
---- | ------------- 
FCSStapCer | Over the last 7 days, how many days did members of your household eat Cereals, such as: (cereals, grains, rice, pasta, bread, sorghum, millet, maize, fonio)   
HDDSStapCer | Yesterday, during the day and night, did members in your household eat Cereals, such as: (cereals, grains,rice, pasta, bread, sorghum, millet, maize, fonio) 
FCSStapCerSRf | Over the last 7 days, what was the main source of Cereals, such as:  (cereals, grains, rice, pasta, bread, sorghum, millet, maize, fonio) 
FCSStapRoot | Over the last 7 days, how many days did members of your household eat Roots and Tubers, such as: (potato, yam, cassava, white sweet potato) 
HDDSStapRoot | Yesterday, during the day and night, did members in your household eat Roots and Tubers, such as: (potato, yam, cassava, white sweet potato)
FCSStapRootSRf | Over the last 7 days, what was the main source of Roots and Tubers, such as: (potato, yam, cassava, white sweet potato) 
FCSPulse | How many days over the last 7 days, did members of your household eat Pulses, such as: (beans, cowpeas, peanuts, lentils, nut, soy, pigeon pea and / or other nuts) 
HDDSPulse | Yesterday, during the day and night, did members in your household eat Pulses, such as: (beans, cowpeas, peanuts, lentils, nut, soy, pigeon pea and / or other nuts) 
FCSPulseSRf | Over the last 7 days, What was the main source of Pulses, such as: (beans, cowpeas, peanuts, lentils, nut, soy, pigeon pea and / or other nuts) 
FCSDairy | Over the last 7 days, how many days did members of your household eat/drink Milk and dairy products, such as:(fresh milk / sour, yogurt, cheese, other dairy products) excluding margarine / butter or small amounts of milk for tea / coffee ?
HDDSDairy | Yesterday, during the day and night, did members in your household eat/drink Milk and dairy products, such as: (fresh milk / sour, yogurt, cheese, other dairy products) excluding margarine / butter or small amounts of milk for tea / coffee ?
FCSDairySRf | Over the last 7 days, what was the main source of Milk and dairy products, such as: (fresh milk / sour, yogurt, cheese, other dairy products)  replace with locally relevant examples excluding margarine / butter or small amounts of milk for tea / coffee ?
FCSPr | Over the last 7 days, how many days did members of your household eat: Meat, fish, eggs, such as: (goat, beef, chicken, pork, blood, fish, including canned tuna, escargot, and / or other seafood, eggs) consumed in large quantities and not as a condiment ?
FCSPrMeatF | Over the last 7 days, how many days did members of your household eat: Flesh/red meat, such as: (beef, pork, lamb, goat, rabbit, chicken, duck, other birds, insects) consumed in large quantities and not as a condiment ?
HDDSPrMeatF | Yesterday, during the day and night, did members in your household eat: Flesh/red meat , such as: (beef, pork, lamb, goat, rabbit, chicken, duck, other birds, insects) consumed in large quantities and not as a condiment ?
FCSPrMeatFSRf | Over the last 7 days,What was the main source of Flesh/red meat , such as: (beef, pork, lamb, goat, rabbit, chicken, duck, other birds, insects) consumed in large quantities and not as a condiment ?
FCSPrMeatO | Over the last 7 days, how many days did members of your household eat: Organ meat, such as: (liver, kidney, heart and / or other organ meats) consumed in large quantities and not as a condiment ?
HDDSPrMeatO | Yesterday, during the day and night, did members in your household eat: Organ meat, such as: (liver, kidney, heart and / or other organ meats) consumed in large quantities and not as a condiment ?
FCSPrMeatOSRf | Over the last 7 days,What was the main source of Organ meat, such as: (liver, kidney, heart and / or other organ meats) consumed in large quantities and not as a condiment ?
FCSPrFish | Over the last 7 days, how many days did members of your household eat: Fish, such as: (fish, including canned tuna, escargot, and / or other seafood) consumed in large quantities and not as a condiment ?
HDDSPrFish | Yesterday, during the day and night, did members in your household eat: Fish, such as: (fish, including canned tuna, escargot, and / or other seafood) consumed in large quantities and not as a condiment ?
FCSPrFishSRf | Over the last 7 days,What was the main source of Fish, such as: (fish, including canned tuna, escargot, and / or other seafood) consumed in large quantities and not as a condiment ?
FCSPrEgg | How many days over the last 7 days, did members of your household eat : Eggs consumed in large quantities and not as a condiment ?
HDDSPrEgg | Yesterday, during the day and night, did members in your household eat: Eggs consumed in large quantities and not as a condiment ?
FCSPrEggSRf | Over the last 7 days,What was the main source of Eggs consumed in large quantities and not as a condiment ?
FCSVeg | Over the last 7 days, how many days did members of your household eat: Vegetables such as (spinach, onion, tomatoes, carrots, peppers, green beans, lettuce, etc.) ?
FCSVegOrg | Over the last 7 days, how many days did members of your household eat: Orange vegetables , such as: (carrot, red pepper, pumpkin, orange sweet potatoes, etc.) ?
HDDSVegOrg | Yesterday, during the day and night, did members in your household eat: Orange vegetables , such as: (carrot, red pepper, pumpkin, orange sweet potatoes, etc.) ?
FCSVegOrgSRf | Over the last 7 days,What was the main source of: Orange vegetables , such as: (carrot, red pepper, pumpkin, orange sweet potatoes, etc.) ?
FCSVegGre | Over the last 7 days, how many days did members of your household eat: Green leafy vegetables, such as: (spinach, broccoli, amaranth and / or other dark green leaves, cassava leaves, etc.) ?
HDDSVegGre | esterday, during the day and night, did members in your household eat: Green leafy vegetables, such as: (spinach, broccoli, amaranth and / or other dark green leaves, cassava leaves, etc.) ?
FCSVegGreSRf | Over the last 7 days,What was the main source of: Green leafy vegetables, such as: (spinach, broccoli, amaranth and / or other dark green leaves, cassava leaves, etc.) ?
FCSVegOth | Over the last 7 days, how many days did members of your household eat: Other Vegetables, such as: (Onion, tomatos, cucumber, radish, green beans, peas, etc) ?
HDDSVegOth | Yesterday, during the day and night, did members in your household eat: Other Vegetables, such as: (Onion, tomatos, cucumber, radish, green beans, peas, etc) ?
FCSVegOthSRf | Over the last 7 days,What was the main source of: Other Vegetables, such as: (Onion, tomatos, cucumber, radish, green beans, peas, etc) ?
FCSFruit | Over the last 7 days, how many days did members of your household eat: Fruits, such as:(banana, apple, lemon, mango, papaya, apricot, peach, etc.) ?
FCSFruitOrg | Over the last 7 days, how many days did members of your household eat: Orange fruits, such as: (mango, papaya, apricot, peach, etc.)
HDDSFruitOrg | Yesterday, during the day and night, did members in your household eat: Orange fruits, such as: (mango, papaya, apricot, peach, etc.)?
FCSFruitOrgSRf | Over the last 7 days,What was the main source of: Orange fruits, such as: (mango, papaya, apricot, peach, etc.) ?
FCSFruitOth | Over the last 7 days, how many days did members of your household eat: Other fruits, such as: (Pinapple, apple, lemon, etc.)?
HDDSFruitOth | Yesterday, during the day and night, did members in your household eat: Orange fruits, such as: (mango, papaya, apricot, peach, etc.)?
FCSFruitOthSRF | Over the last 7 days, how many days did members of your household eat: Other fruits, such as: (Pinapple, apple, lemon, etc.)?
FCSFat | Over the last 7 days,What was the main source of:  Fats and oils,such as: (vegetable oil, palm oil, shea butter, margarine, other fats /oil)?
HDDSFat | Yesterday, during the day and night, did members in your household eat: Fats and oils,such as: (vegetable oil, palm oil, shea butter, margarine, other fats /oil)?
FCSFatSRf | Over the last 7 days,What was the main source of:  Fats and oils,such as: (vegetable oil, palm oil, shea butter, margarine, other fats /oil)?
FCSSugar | Over the last 7 days,What was the main source of:  Sugar and sweets, such as: (sugar, honey, jam, cakes, candy, cookies, pastries, cakes and other sweet sugary drinks)?
HDDSSugar | Yesterday, during the day and night, did members in your household eat: Sugar and sweets, such as:(sugar, honey, jam, cakes, candy, cookies, pastries, cakes and other sweet sugary drinks)?
FCSSugarSRf | Over the last 7 days,What was the main source of: Sugar and sweets, such as: (sugar, honey, jam, cakes, candy, cookies, pastries, cakes and other sweet sugary drinks)?
FCSCond | Over the last 7 days, What was the main source of: Condiments/Spices: such as: (tea, coffee / cocoa, salt, garlic, spices, yeast / baking powder, tomato / sauce, meat or fish as a condiment, condiments including small amount of milk / tea coffee)?
HDDSCond | Yesterday, during the day and night, did members in your household eat: Condiments/Spices: such as: (tea, coffee / cocoa, salt, garlic, spices, yeast / baking powder, tomato / sauce, meat or fish as a condiment, condiments including small amount of milk / tea coffee)?
FCSCondSRf | Over the last 7 days,What was the main source of: Condiments/Spices: such as: (tea, coffee / cocoa, salt, garlic, spices, yeast / baking powder, tomato / sauce, meat or fish as a condiment, condiments including small amount of milk / tea coffee)?
 
