# Visualizing CH Direct Food security Indicators

Visualizing the phasing of areas in maps and tables  according to the different food security indicators can give users a chance to view contemplate/synthesize the results.  The resources below, illustrate two methods for visualizing the results: via the Matrice Intermediare (.csv file) from the processed survey file itself.

## Visualizing CH Direct Food security Indicators from Matrice Intermediare (.csv file)

After survey teams have generated the .csv for the  matrice intermediare, the R script below can be used for creating maps and tables of the Food Security Direct Evidence.

### Overview video 

<iframe width="560" height="315" src="https://www.youtube.com/embed/6A5EpqqDOdk" frameborder="0" allowfullscreen></iframe>



### Example matrice intermediare (.csv file)

Here is the example matrice intermediare (.csv) generated from processes in the last chapter:

[matrice_intermediaire_direct_en.csv](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/outputs/matrice_intermediaire_direct_en.csv) 

### Syntax

Here is the syntax to visualize the CH Direct Food security Indicators
[example_CH_preliminaryFSresults_fromcsv](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/syntax/example_CH_preliminaryFSresults_fromcsv.zip) 


## Visualizing CH Direct Food security Indicators directly from processed data set 

Alternatively, teams can use the R script below to create maps and tables of the Food Security Direct Evidence directly from the processed dataset.  


### Overview video 

<iframe width="560" height="315" src="https://www.youtube.com/embed/6A5EpqqDOdk" frameborder="0" allowfullscreen></iframe>

### Example processed data set

Here is the example processed data set:
[exampledataEnglish_processed](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/example_datasets/exampledataEnglish_processed.sav) 

### Syntax

Here is the syntax to visualize the CH Direct Food security Indicators from the processed dataset
[example_CH_preliminaryFSresults_fromspss](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/syntax/example_CH_preliminaryFSresults_fromspss.zip) 





