--- 
title: "A Guide to Standardized Collection, Processing and Visualization of Cadre Harmonise Food Security Indicators"
author:
  - Research, Assesment and Monitoring (RAM) Unit
  - Regional Bureau for West & Central Africa, World Food Programme
  - rbd.vam@wfp.org
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Purpose & How to use this Guide

This guide proposes a uniform set of tools for the collection, processing, analysis and visualization of key food security direct evidence indicators and technical variables used in the Cadre Harmonise process.  

Briefly summarized, this guide introduces questionnaires, electronic data colection forms and syntax to collect and calculate standardized data.  Standardized data improves comparability across and allows for faster and greater use of data tools and visualizations.

A brief overview of the chapters in this guide:

1. [Chapter 2 Setting up R & Rstudio](https://wfp-vam.github.io/RBD_FS_CH_guide_EN/setting-up-r-rstudio.html) - how to install R & Rstudio software ; how to add require packages an overview on how to use Rmarkdown


**Chapter 1 Purpose & How to use this Guide** - where you are now, reading through could help you find the right place to go
**Chapter 2 Setting up R & Rstudio** - how to install R & Rstudio software ; how to add require packages an overview on how to use Rmarkdown
**Chapter 3 Geocodes** - explains how/why to put geo-codes into the data collection sheets to speed up mapping and data processing
**Chapter 4 Household Hunger Scale** - paper and electronic versions of standardized questionnaire and syntax in SPSS and R for calculating the Household Hunger Scale indicator
**Chapter 5 reduced Coping Strategy Index** - paper and electronic versions of standardized questionnaire and syntax in SPSS and R for calculating the reduced Coping Strategy Index indicator
**Chapter 6 Food Consumption Score & Household Dietary Diversity Score**  - paper and electronic versions of standardized questionnaire and syntax in SPSS and R for calculating the Food Consumption Score/Groups and Household Dietary Diversity Score.
**Chapter 7  Livelihood Coping Strategies** - paper and electronic versions of standardized questionnaire and syntax in SPSS and R for calculating maximum coping strategy used for CARI light version and ENA version of the Livelihood Coping Strategies module.
**Chapter 8 Combined Questionnaires and Syntaxes** - puts the questionnaires and syntaxes from chapter 4 - 7 together 
**Chapter 9 Data Quality Monitoring Report** provides instruction and generic data quality report syntax which can be run using R and the survey raw data in spss format
**Chapter 10 Calculating Matrice Intermediare** provides instruction and a generic syntax to produce a matrice intermediare of direct food security indicators and geocodes from the processed dataset in spss format
**Chapter 11 Visualizing CH Direct Food security Indicators** using the matrice intermediare or processed dataset - make maps and tables of the phasing of areas by indicator 

*About software* - while use of the software R & Rstudio is necessary to produce the outputs in chapters 7, 8 and 9, users do not need to disrupt their normal analysis processes - most commonly in SPSS.  The R syntax used for the data quality management is compatible with the "raw data" that is downloaded from data collection servers.  The R syntax used to produce the `matrice intermediare` is compatible with the "processed data" (calculated indicators and in spss format.  

*About the example datasets* - for this guide, two "semi-fictitious" datasets were created by randomly selecting and de-identifiying respondent answers from surveys from two countries.  The results are "safe" datasets that serve as an example:

1. [exampledataEnglish_raw](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/example_datasets/exampledataEnglish_raw.sav) - is what a "raw" data looks like when downloaded from ODK server in spss format.  

2. [exampledataEnglish_processed](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/example_datasets/exampledataEnglish_processed.sav) - mirrors what a processed data looks like - i.e. calculated indicators and a weight variable.  




# Setting up R & Rstudio 

## Installing R & Rstudio

<iframe width="560" height="315" src="https://www.youtube.com/embed/orjLGFmx6l4" frameborder="0" allowfullscreen></iframe>

### R

To download R, go to CRAN, the comprehensive R archive network. CRAN is composed of a set of mirror servers distributed around the world and is used to distribute R and R packages. Don’t try and pick a mirror that’s close to you: instead use the cloud mirror, https://cloud.r-project.org, which automatically figures it out for you.
A new major version of R comes out once a year, and there are 2-3 minor releases each year. It’s a good idea to update regularly. Upgrading can be a bit of a hassle, especially for major versions, which require you to reinstall all your packages, but putting it off only makes it worse. https://r4ds.had.co.nz/introduction.html


### RStudio 

RStudio is an integrated development environment, or IDE, for R programming. Download and install it from http://www.rstudio.com/download. RStudio is updated a couple of times a year. When a new version is available, RStudio will let you know. It’s a good idea to upgrade regularly so you can take advantage of the latest and greatest features. For this book, make sure you have at least RStudio 1.0.0.
When you start RStudio, you’ll see two key regions in the interface:

For now, all you need to know is that you type R code in the console pane, and press enter to run it. You’ll learn more as we go along!

copied from https://r4ds.had.co.nz/introduction.html (gonna figure out how to cite it)

## Installing packages

<iframe width="560" height="315" src="https://www.youtube.com/embed/-wTcDqJWSzA" frameborder="0" allowfullscreen></iframe>

You’ll also need to install some R packages. An R package is a collection of functions, data, and documentation that extends the capabilities of base R. Using packages is key to the successful use of R. The majority of the packages that you will learn in this book are part of the so-called tidyverse. The packages in the tidyverse share a common philosophy of data and R programming, and are designed to work together naturally.
You can install the complete tidyverse with a single line of code:

```{r eval=FALSE}
install.packages("tidyverse")
```

On your own computer, type that line of code in the console, and then press enter to run it. R will download the packages from CRAN and install them on to your computer. If you have problems installing, make sure that you are connected to the internet, and that https://cloud.r-project.org/ isn’t blocked by your firewall or proxy.
You will not be able to use the functions, objects, and help files in a package until you load it with library(). Once you have installed a package, you can load it with the library() function:

library(tidyverse)

