---
title: 'change name'
author: "WFP VAM"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)

library(haven)
library(labelled)
library(tidyverse)
library(tidyselect)
library(plotly)
library(ggmosaic)
library(Hmisc)
library(kableExtra)
library(janitor)

data <- read_sav("C:/RCA_202011_ENSAN/1_RawData/data.sav")
data <- to_factor(data)

data <- data %>% rename(enumerator = q1.9a, teamleader = q1.9b)


#convert date to week number

#sample size by team/operator/region
samplecountsadm1 <- data %>% group_by(adm1_name) %>%count() 
samplecountsteam <- data %>% 
  group_by(teamleader) %>%
  count() 
samplecountsenumerator <- data %>% 
  group_by(teamleader, enumerator) %>%
  count() 


#Calculate Indicators
#calculate rCSI
data <- data %>% mutate(rcsi = rCSILessQlty + rCSIBorrow * 2 + rCSIMealNb + rCSIMealSize + rCSIMealAdult * 3)

#FCG
#add Cereals & Tubers together
data <- data  %>% mutate(fcsstap = fcscer + fcsroottub) %>% mutate(fcsstap = case_when(fcsstap > 7 ~ 7, TRUE ~ fcsstap))
#create FCS with food groups
data <- data  %>% mutate(fcs = (2 * fcsstap) + (3 * fcspulse)+ (4*fcspr) +fcsveg  +fcsfruit +(4*fcsdairy) + (0.5*fcsfat) + (0.5*fcssugar))
#create food consumption groups with 21/35 cutoffs
data <- data  %>% mutate(
  fcscat21 = case_when(
  fcs <= 21 ~ "poor", between(fcs, 21.5, 35) ~ "borderline", fcs >= 35 ~ "acceptable"))

#
fcsplot <- data %>% ggplot(aes(x=fcs, y=enumerator)) +geom_violin() +facet_grid(teamleader ~ adm1_name, scales = "free")
fcsplot <- fcsplot +stat_summary(fun.y=median, geom="point", size=3, color="blue") +stat_summary(fun.data=mean_sdl, mult=1, geom="pointrange", color="red") + theme_minimal()
fcsplot <- fcsplot +labs(title = "food consumption score",
              subtitle = "values by enumerator/team leader",
              caption = "Shape: Density Curve 
                         Red line: 95% Confidence Interval
                         Red dot: mean
                         Blue dot: median
                        ")


rcsiplot <- data %>% ggplot(aes(x=rcsi, y=enumerator)) +geom_violin()  +facet_grid(teamleader ~ adm1_name, scales = "free")
rcsiplot <- rcsiplot +stat_summary(fun.y=median, geom="point", size=3, color="blue") +stat_summary(fun.data=mean_sdl, mult=1, geom="pointrange", color="red") + theme_minimal()
rcsiplot <- rcsiplot +labs(title = "reduced coping strategy",
              subtitle = "values by enumerator/team leader",
              caption = "Shape: Density Curve
                         Red line: 95% Confidence Interval
                         Red dot: mean
                         Blue dot: median
                        ")

#FCG by enumerator by adm1
FCGenumadm1table_long <- data %>% 
    group_by(adm1_name, enumerator) %>%
    count(fcscat21) 

mosaicfcg <- FCGenumadm1table_long %>%  ggplot() +geom_mosaic(aes(x=product(enumerator), fill=fcscat21, weight = n)) +facet_wrap(. ~ adm1_name) +scale_fill_manual(values=c("#27AE60","#F1C40F","#C0392B")) +labs(x ="", y = "", position = "center") +theme_minimal()  +theme(axis.text.y = element_blank())
mosaicfcg <- mosaicfcg +labs(title = "food consumption score",
              subtitle = "values by enumerator/team leader",
              caption = "Width of bar = number of interview completed
                        *will be fixed to show enumerator name*
                        ")


#calculates food expenditure
data <- data  %>% mutate_at(vars(ends_with("mn")|ends_with("crd")|ends_with("np")), replace_na, 0)

```



#### Sample Counts & Progress

```{r}
kable(samplecountsadm1) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
kable(samplecountsteam) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
kable(samplecountsenumerator) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```





#### Tracking key indicators

```{r, fig.width=10, fig.height=10, fig.fullwidth=TRUE}
rcsiplot
```


```{r, fig.width=10, fig.height=10, fig.fullwidth=TRUE}
fcsplot
```

```{r, fig.width=10, fig.height=10, fig.fullwidth=TRUE}
mosaicfcg
```
